image: debian:bullseye

before_script:
  - chmod +x scripts/install_dependencies.sh
  - ./scripts/install_dependencies.sh
simple_test:
  variables:
    FAKE_DISK: "fake_disk.ext4"
    FAKE_MOUNTPOINT: "fake_mountpoint"
  script:
    - chmod +x scripts/test.sh
    - ./scripts/test.sh svg png ascii
  artifacts:
    when: always
    paths:
      - "*.svg"
      - "*.png"
      - "*.ascii"
      - "*.txt"
      - "*.log"

interactive_plot_test:
  variables:
    FAKE_DISK: "fake_disk.ext4"
    FAKE_MOUNTPOINT: "fake_mountpoint"
  script:
    - chmod +x scripts/test.sh
    - ./scripts/test.sh html
  artifacts:
    when: always
    paths:
      - "*.txt"
      - "*.log"
      - "*.html"

  
