image: debian:bullseye

before_script:
    - apt-get update
    - apt-get install -qqy --no-install-recommends python3 python3-pip git
    - pip3 install git+https://github.com/antmicro/tuttest.git

simple_test:
    script:
        - ./scripts/test.sh
    artifacts:
        when: always
        paths:
            - "plot.svg"
            - "plot.png"
            - "plot.ascii"
            - "plot.html"
            - "example.log"
            - "example.txt"
