name: Sargraph tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    readme-tests:
        runs-on: ubuntu-latest
        container:
            image: debian:bullseye
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3
            - name: Install dependencies
              run: |
                  apt-get update
                  apt-get install -qqy --no-install-recommends python3 python3-pip git
                  pip3 install git+https://github.com/antmicro/tuttest.git
            - name: Run README.md snippets
              run: |
                  ./scripts/test.sh
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: sargraph-sample-graphs
                  path: |
                      *.svg
                      *.png
                      *.ascii
                      *.html
                      *.txt
                      *.log
